//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by FineUI.Core.
//     
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUI.Core.EmptyProject.Pages
{
	public partial class HelloModel
	{
		protected FineUI.Core.Button btnHello;
	}
}
