//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by FineUI.Core.
//     
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUI.Core.EmptyProject.Pages
{
	public partial class IndexModel
	{
		protected FineUI.Core.Panel mainPanel;
		protected FineUI.Core.Panel sidebarRegion;
		protected FineUI.Core.Panel sideheaderTopPanel;
		protected FineUI.Core.Panel leftPanel;
		protected FineUI.Core.Tree treeMenu;
		protected FineUI.Core.Panel bodyRegion;
		protected FineUI.Core.Panel topPanel;
		protected FineUI.Core.Button btnThemeSelect;
		protected FineUI.Core.TabStrip mainTabStrip;
		protected FineUI.Core.Tab tabHomepage;
		protected FineUI.Core.Window windowThemeRoller;
	}
}
