//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by FineUI.Core.
//     
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUI.Core.EmptyProject.Pages
{
	public partial class LoginModel
	{
		protected FineUI.Core.Window Window1;
		protected FineUI.Core.SimpleForm SimpleForm1;
		protected FineUI.Core.TextBox tbxUserName;
		protected FineUI.Core.TextBox tbxPassword;
		protected FineUI.Core.Toolbar Toolbar1;
		protected FineUI.Core.Button btnLogin;
		protected FineUI.Core.Button btnReset;
	}
}
